name: Comment on Newly Merged PR with Submission Label

on:
  push:
    branches:
      - main

jobs:
  comment-on-merged-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: load previously processed prs
      id: load-processed-prs
      run: |
        if [ -f processed_prs.yml ]; then
          PROCESSED=$(cat processed_prs.yml)
        else
          PROCESSED="[]"
        fi
        echo "::set-output name=processed_prs::$PROCESSED"

    - name: Get  list of merged prs
      id: get-prs
      run: |
        PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=${{ github.ref }}")
        echo "::set-output name=prs::$PRS"

    - name: Filter newly merged prs with submission label
      id: filter-prs
      run: |
        PRS=${{ steps.get-prs.outputs.prs }}
        PROCESSED=${{ steps.load-processed-prs.outputs.processed_prs }}
        PRS_WITH_LABEL=$(echo $PRS | jq '[.[] | select(.merged_at != null and (.labels | any(.name == "submission")) and (.id as $id | IN($PROCESSED[]; $id) | not))]')
        echo "::set-output name=prs_with_label::$PRS_WITH_LABEL"

    - name: Comment on recently merged PRs
      if: steps.filter-prs.outputs.prs_with_label != '[]'
      run: |
        PRS_WITH_LABEL=${{ steps.filter-prs.outputs.prs_with_label }}
        for row in $(echo "${PRS_WITH_LABEL}" | jq -r '.[] | @base64'); do
          _jq() {
            echo ${row} | base64 --decode | jq -r ${1}
          }
          PR_NUMBER=$(_jq '.number')
          COMMENT="https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d "{\"body\": \"${COMMENT}\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
          # Add the merged PR ID to the processed list
          echo "$(_jq('.id'))" >> processed_prs.yml
        done

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
